/**
 * Seed script: WCAG 2.2 (A + AA) Test Case Library
 *
 * Populates the `TestCaseLibrary` collection with one generic, reusable test
 * case per WCAG 2.2 Level A / Level AA success criterion. Admins can later
 * import/clone these into a project's actual TestCase records (see
 * models/test-case.ts `libId` field).
 *
 * Coverage note: WCAG 2.2 defines 56 Level A/AA success criteria if 4.1.1
 * "Parsing" is counted (it's officially deprecated/removed in 2.2 since
 * modern browsers no longer need it, but is still commonly tested in
 * practice) — 55 if it's excluded. This seed includes it (LIB-054) so the
 * library covers every A/AA criterion; deactivate it (isActive: false) if
 * you want strict WCAG 2.2 conformance instead.
 *
 * disabilityTypes reuses the same vocabulary as
 * User.testerProfile.disabilityTypes: "blind" | "low_vision" | "deaf" |
 * "hard_of_hearing" | "motor" | "cognitive" (that field also allows "none",
 * which doesn't apply here since every entry targets at least one type).
 * A hearing-related criterion is tagged with both "deaf" and
 * "hard_of_hearing" since both groups are affected. See
 * models/TestCaseLibrary.ts for details.
 *
 * Run (tsx resolves the "@/*" path alias via tsconfig.json automatically):
 *   npx tsx --env-file=.env.local scripts/seed-library.ts
 *
 * The --env-file flag is required: scripts run outside Next.js so
 * MONGODB_URI / MONGODB_DB from .env.local aren't picked up otherwise, and
 * a plain top-level process.loadEnvFile() call here wouldn't run in time —
 * static `import`s (below) are hoisted and evaluated before it, so
 * lib/mongodb.ts would already have thrown by the time env vars loaded.
 */

import mongoose from "mongoose";
import { connectToDatabase } from "@/lib/mongodb";
import TestCaseLibrary, { type ITestCaseLibrary } from "@/models/TestCaseLibrary";

type SeedEntry = Omit<ITestCaseLibrary, "createdAt" | "updatedAt">;

const LIBRARY_SEED: SeedEntry[] = [
  // ─── 1. Perceivable ───────────────────────────────────────────────────
  {
    libId: "LIB-001",
    wcagVersion: "2.2",
    wcagCriterion: "1.1.1",
    wcagTitle: "Non-text Content",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่ารูปภาพ/ไอคอนมีคำอธิบาย Alt Text",
    description: "ตรวจสอบว่าเนื้อหาที่ไม่ใช่ข้อความ (รูปภาพ, ไอคอน, ปุ่มรูปภาพ) มีข้อความทางเลือกที่สื่อความหมายเทียบเท่า",
    steps: ["เปิด Screen Reader", "เลื่อนโฟกัสไปที่รูปภาพ/ไอคอนทุกจุด", "ฟังเสียงที่ SR อ่าน"],
    expectedResult: "Screen Reader อ่านคำอธิบายที่สื่อความหมายของรูปภาพได้",
    failCondition: "อ่านชื่อไฟล์, 'กราฟิกไม่มีชื่อ', หรือเงียบข้าม",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีรูปภาพ ไอคอน หรือปุ่มรูปภาพ",
    isActive: true,
  },
  {
    libId: "LIB-002",
    wcagVersion: "2.2",
    wcagCriterion: "1.2.1",
    wcagTitle: "Audio-only and Video-only (Prerecorded)",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ transcript สำหรับไฟล์เสียงหรือวิดีโอไม่มีเสียง",
    description: "ตรวจสอบว่าไฟล์ audio-only หรือ video-only ที่บันทึกไว้ล่วงหน้ามีทางเลือกข้อความ (transcript/text alternative) ครบถ้วน",
    steps: ["เปิดไฟล์ audio-only หรือ video-only", "ตรวจสอบว่ามีลิงก์/ปุ่มเข้าถึง transcript", "เปรียบเทียบเนื้อหา transcript กับเนื้อหาจริง"],
    expectedResult: "มี transcript ที่ถ่ายทอดเนื้อหาเสียง/ภาพได้ครบถ้วน",
    failCondition: "ไม่มี transcript หรือ transcript ไม่ครบเนื้อหา",
    disabilityTypes: ["deaf", "hard_of_hearing", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีไฟล์เสียงหรือวิดีโอที่ไม่มีภาพเคลื่อนไหว",
    isActive: true,
  },
  {
    libId: "LIB-003",
    wcagVersion: "2.2",
    wcagCriterion: "1.2.2",
    wcagTitle: "Captions (Prerecorded)",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ closed caption ของวิดีโอที่บันทึกไว้ล่วงหน้า",
    description: "ตรวจสอบว่าวิดีโอที่มีเสียงพูดและบันทึกไว้ล่วงหน้ามี caption ที่ตรงกับบทสนทนาและเสียงประกอบสำคัญ",
    steps: ["เปิดวิดีโอที่มีเสียงพูด", "เปิด caption/subtitle", "เปรียบเทียบข้อความ caption กับเสียงพูดจริง"],
    expectedResult: "caption ตรงกับบทสนทนาและเสียงประกอบสำคัญ (เช่น เสียงเตือน) ครบถ้วน",
    failCondition: "ไม่มี caption, caption ผิดเวลา, หรือขาดข้อความบางส่วน",
    disabilityTypes: ["deaf", "hard_of_hearing"],
    assistiveTech: [],
    applicableWhen: "หน้ามีวิดีโอที่มีเสียงพูดและบันทึกไว้ล่วงหน้า",
    isActive: true,
  },
  {
    libId: "LIB-004",
    wcagVersion: "2.2",
    wcagCriterion: "1.2.3",
    wcagTitle: "Audio Description or Media Alternative (Prerecorded)",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบคำบรรยายเสียง (Audio Description) หรือทางเลือกข้อความสำหรับวิดีโอ",
    description: "ตรวจสอบว่าวิดีโอที่มีข้อมูลภาพสำคัญมี audio description หรือ transcript ที่บรรยายภาพให้ผู้ใช้ที่มองไม่เห็นเข้าใจเนื้อหาได้",
    steps: ["เปิดวิดีโอพร้อม Screen Reader", "ตรวจสอบว่ามี Audio Description แทรกอธิบายภาพ หรือมี transcript ที่บรรยายภาพครบถ้วน"],
    expectedResult: "ผู้ใช้ที่มองไม่เห็นเข้าใจเนื้อหาภาพในวิดีโอได้ผ่าน Audio Description หรือ transcript",
    failCondition: "ไม่มี Audio Description และไม่มี transcript ที่บรรยายภาพ",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีวิดีโอที่มีข้อมูลภาพสำคัญ (เช่น ข้อความบนจอ, การกระทำที่ไม่มีเสียงประกอบ)",
    isActive: true,
  },
  {
    libId: "LIB-005",
    wcagVersion: "2.2",
    wcagCriterion: "1.2.4",
    wcagTitle: "Captions (Live)",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ Caption สำหรับเนื้อหาถ่ายทอดสด",
    description: "ตรวจสอบว่าเนื้อหาถ่ายทอดสดที่มีเสียงพูดมี caption แบบเรียลไทม์",
    steps: ["เปิดการถ่ายทอดสด", "ตรวจสอบว่ามี caption ปรากฏ real-time"],
    expectedResult: "มี caption ที่ตรงกับเสียงพูดแบบเรียลไทม์",
    failCondition: "ไม่มี caption หรือ caption ล่าช้า/ไม่ตรงกับเสียง",
    disabilityTypes: ["deaf", "hard_of_hearing"],
    assistiveTech: [],
    applicableWhen: "หน้ามีการถ่ายทอดสดที่มีเสียงพูด (live audio content)",
    isActive: true,
  },
  {
    libId: "LIB-006",
    wcagVersion: "2.2",
    wcagCriterion: "1.2.5",
    wcagTitle: "Audio Description (Prerecorded)",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ Audio Description แทรกในวิดีโอโดยตรง",
    description: "ตรวจสอบว่าวิดีโอที่บันทึกไว้ล่วงหน้าและมีข้อมูลภาพสำคัญมี audio description track แทรกอยู่ในตัววิดีโอเอง",
    steps: ["เปิดวิดีโอ", "ฟัง Audio Description track", "ตรวจสอบว่าอธิบายภาพครบถ้วนโดยไม่ต้องพึ่ง transcript แยก"],
    expectedResult: "มี audio description แทรกในวิดีโอโดยตรง อธิบายข้อมูลภาพที่จำเป็น",
    failCondition: "ไม่มี audio description track ในวิดีโอ",
    disabilityTypes: ["blind"],
    assistiveTech: [],
    applicableWhen: "หน้ามีวิดีโอที่บันทึกไว้ล่วงหน้าและมีข้อมูลภาพสำคัญ",
    isActive: true,
  },
  {
    libId: "LIB-007",
    wcagVersion: "2.2",
    wcagCriterion: "1.3.1",
    wcagTitle: "Info and Relationships",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบโครงสร้าง Heading ถูกต้อง",
    description: "ตรวจสอบว่าโครงสร้าง/ความสัมพันธ์ของเนื้อหา (heading, list, table, form label) ถูกกำหนดด้วย markup ที่ถูกต้อง ไม่ใช่แค่ style ทางสายตา",
    steps: ["กดคีย์ลัด H ไล่โครงสร้าง Heading ด้วย Screen Reader", "ตรวจสอบลำดับ h1→h2→h3", "ตรวจสอบ list/table/form ว่าใช้ markup ที่ถูกต้อง"],
    expectedResult: "โครงสร้าง heading/list/table/form ถูกกำหนดด้วย markup ที่ถูกต้องและลำดับสมเหตุสมผล",
    failCondition: "ลำดับ heading กระโดดข้าม (เช่น h1→h3), หรือใช้ text ธรรมดาจัด style แทน markup จริง",
    disabilityTypes: ["blind", "cognitive"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ทุกหน้าที่มีโครงสร้างเนื้อหา heading/list/table/form",
    isActive: true,
  },
  {
    libId: "LIB-008",
    wcagVersion: "2.2",
    wcagCriterion: "1.3.2",
    wcagTitle: "Meaningful Sequence",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบลำดับการอ่านสมเหตุสมผล",
    description: "ตรวจสอบว่าลำดับที่ Screen Reader อ่านเนื้อหาตรงกับลำดับที่มีความหมายตามที่แสดงผลด้วยสายตา",
    steps: ["ปิด CSS หรือใช้ Screen Reader อ่านทั้งหน้าตามลำดับ DOM", "เปรียบเทียบกับลำดับที่แสดงผลบนหน้าจอ"],
    expectedResult: "ลำดับการอ่านของ Screen Reader ตรงกับลำดับเนื้อหาที่มีความหมาย",
    failCondition: "ลำดับการอ่านสลับหรือไม่สัมพันธ์กับลำดับที่แสดงผลจริง",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้าที่ใช้ CSS จัดตำแหน่งเนื้อหาต่างจากลำดับ DOM (เช่น grid/flex layout)",
    isActive: true,
  },
  {
    libId: "LIB-009",
    wcagVersion: "2.2",
    wcagCriterion: "1.3.3",
    wcagTitle: "Sensory Characteristics",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่าไม่ใช้รูปร่าง/สี/ตำแหน่งเพียงอย่างเดียวสื่อความหมาย",
    description: "ตรวจสอบว่าคำแนะนำการใช้งานไม่ได้อ้างอิงลักษณะทางประสาทสัมผัสอย่างเดียว เช่น 'ปุ่มสีเขียวทางขวา' โดยไม่มีข้อความ/label กำกับ",
    steps: ["อ่านคำแนะนำ/instruction ทุกจุดในหน้า", "ตรวจสอบว่าอ้างอิงถึง shape, color, size, ตำแหน่งเพียงอย่างเดียวหรือไม่"],
    expectedResult: "คำแนะนำระบุ label/ชื่อของ element ควบคู่ไปกับลักษณะทางประสาทสัมผัส",
    failCondition: "คำแนะนำอ้างอิงเฉพาะรูปร่าง สี ขนาด หรือตำแหน่ง โดยไม่มีชื่อ/label กำกับ",
    disabilityTypes: ["blind", "low_vision"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีคำแนะนำที่อ้างอิงลักษณะภาพของ element (เช่น 'คลิกปุ่มกลม')",
    isActive: true,
  },
  {
    libId: "LIB-010",
    wcagVersion: "2.2",
    wcagCriterion: "1.3.4",
    wcagTitle: "Orientation",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่าหน้าไม่ล็อกการหมุนจอ",
    description: "ตรวจสอบว่าเนื้อหาใช้งานได้ทั้งแนวตั้งและแนวนอน ไม่ถูกล็อก orientation โดยไม่จำเป็น",
    steps: ["หมุนอุปกรณ์/เปลี่ยน orientation เป็นแนวตั้งและแนวนอน", "ตรวจสอบว่าเนื้อหาปรับตัวและใช้งานได้ทั้งสองแนว"],
    expectedResult: "เนื้อหาใช้งานได้ทั้งแนวตั้งและแนวนอน เว้นแต่ orientation เดียวจำเป็นต่อฟังก์ชัน (เช่น แอปเช็คแบงก์)",
    failCondition: "หน้าถูกล็อกให้แสดงเฉพาะแนวเดียวโดยไม่มีเหตุผลจำเป็น",
    disabilityTypes: ["motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "หน้าที่ใช้งานบนอุปกรณ์พกพา/แท็บเล็ตที่ปรับ orientation ได้",
    isActive: true,
  },
  {
    libId: "LIB-011",
    wcagVersion: "2.2",
    wcagCriterion: "1.3.5",
    wcagTitle: "Identify Input Purpose",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบช่องกรอกรองรับ Auto-fill",
    description: "ตรวจสอบว่าช่อง input ที่เก็บข้อมูลส่วนบุคคลทั่วไป (ชื่อ, ที่อยู่, อีเมล ฯลฯ) ระบุ purpose ด้วย autocomplete attribute ที่ browser/AT เข้าใจได้",
    steps: ["ตรวจสอบ HTML ของช่อง input ที่เก็บข้อมูลส่วนบุคคล", "ตรวจสอบว่ามี autocomplete attribute ที่ถูกต้องตรงกับ purpose"],
    expectedResult: "ช่อง input มี autocomplete attribute ที่ตรงตาม purpose มาตรฐาน (เช่น autocomplete=\"email\")",
    failCondition: "ช่องกรอกข้อมูลส่วนบุคคลไม่มี autocomplete attribute หรือระบุผิดประเภท",
    disabilityTypes: ["cognitive", "motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "ฟอร์มที่มีช่องกรอกข้อมูลส่วนบุคคลมาตรฐาน (ชื่อ, ที่อยู่, อีเมล, เบอร์โทร)",
    isActive: true,
  },
  {
    libId: "LIB-012",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.1",
    wcagTitle: "Use of Color",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่าไม่ใช้สีเพียงอย่างเดียวสื่อความหมาย",
    description: "ตรวจสอบว่าข้อมูล/สถานะ/การกระทำที่สื่อด้วยสี ยังมีตัวบ่งชี้อื่นควบคู่ (ข้อความ, ไอคอน, รูปแบบเส้น)",
    steps: ["เปิดหน้าด้วยโหมด grayscale หรือ color blindness simulator", "ตรวจสอบว่ายังเข้าใจสถานะ/ข้อมูลได้ครบถ้วน"],
    expectedResult: "ข้อมูล/สถานะที่ใช้สีสื่อความหมายยังมีตัวบ่งชี้อื่น (ข้อความ/ไอคอน) กำกับด้วย",
    failCondition: "ข้อมูลสำคัญ (เช่น error field, สถานะ) สื่อด้วยสีเพียงอย่างเดียว",
    disabilityTypes: ["blind", "low_vision"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้าใช้สีเพื่อสื่อสถานะ/ข้อมูล เช่น error, ลิงก์, กราฟ",
    isActive: true,
  },
  {
    libId: "LIB-013",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.2",
    wcagTitle: "Audio Control",
    wcagLevel: "A",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่าสามารถหยุด/ปิดเสียงอัตโนมัติได้",
    description: "ตรวจสอบว่าเสียงที่เล่นอัตโนมัตินานเกิน 3 วินาทีมีกลไกให้หยุด/ปิด/ปรับระดับเสียงแยกจากระบบ",
    steps: ["โหลดหน้าที่มีเสียงเล่นอัตโนมัติ", "ตรวจสอบว่ามีปุ่ม pause/stop/mute ที่เข้าถึงได้ง่าย"],
    expectedResult: "สามารถหยุด/ปิด/ปรับระดับเสียงอัตโนมัติได้โดยไม่ต้องปรับระดับเสียงของอุปกรณ์ทั้งระบบ",
    failCondition: "เสียงเล่นอัตโนมัติต่อเนื่องโดยไม่มีปุ่มหยุด/ปิด",
    disabilityTypes: ["deaf", "hard_of_hearing", "cognitive"],
    assistiveTech: [],
    applicableWhen: "หน้ามีเสียง/วิดีโอที่เล่นอัตโนมัติเมื่อโหลดหน้า",
    isActive: true,
  },
  {
    libId: "LIB-014",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.3",
    wcagTitle: "Contrast (Minimum)",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ Contrast Ratio ของข้อความ",
    description: "ตรวจสอบว่าข้อความและพื้นหลังมีความต่างของสี (contrast ratio) เพียงพอต่อการอ่าน",
    steps: ["ใช้เครื่องมือวัด contrast ratio (เช่น Color Contrast Analyzer)", "ตรวจสอบข้อความปกติและข้อความขนาดใหญ่/ตัวหนาทุกจุด"],
    expectedResult: "ข้อความปกติมี contrast ratio อย่างน้อย 4.5:1 และข้อความขนาดใหญ่อย่างน้อย 3:1",
    failCondition: "พบข้อความที่มี contrast ต่ำกว่าเกณฑ์",
    disabilityTypes: ["low_vision"],
    assistiveTech: ["magnifier"],
    applicableWhen: "หน้ามีข้อความและพื้นหลังที่ต้องอ่าน",
    isActive: true,
  },
  {
    libId: "LIB-015",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.4",
    wcagTitle: "Resize Text",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบการซูมข้อความ 200%",
    description: "ตรวจสอบว่าเนื้อหาและฟังก์ชันยังใช้งานได้ปกติเมื่อขยายขนาดข้อความถึง 200% ด้วย browser zoom",
    steps: ["ซูมหน้าเว็บด้วย browser zoom ถึง 200%", "ตรวจสอบว่าข้อความและฟังก์ชันยังใช้งานได้ครบถ้วน ไม่มีการตัดข้อความ/ซ้อนทับ"],
    expectedResult: "เนื้อหาและฟังก์ชันทำงานได้ปกติที่ 200% โดยไม่ต้องเลื่อนแนวนอน (ยกเว้นกรณีจำเป็น)",
    failCondition: "ข้อความถูกตัด ซ้อนทับ หรือฟังก์ชันใช้งานไม่ได้เมื่อซูม 200%",
    disabilityTypes: ["low_vision"],
    assistiveTech: ["magnifier"],
    applicableWhen: "ทุกหน้าที่มีข้อความ",
    isActive: true,
  },
  {
    libId: "LIB-016",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.5",
    wcagTitle: "Images of Text",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบว่าใช้ข้อความจริงแทนรูปภาพของข้อความ",
    description: "ตรวจสอบว่าข้อความในหน้าใช้ข้อความจริง (real text) แทนรูปภาพที่มีข้อความอยู่ในภาพ ยกเว้นกรณีจำเป็น",
    steps: ["ตรวจสอบว่าข้อความในหน้าใช้ข้อความจริงแทนรูปภาพของข้อความ", "หากมีรูปภาพข้อความ ตรวจสอบว่าจำเป็น (เช่นโลโก้) หรือปรับแต่งได้"],
    expectedResult: "ใช้ข้อความจริงแทนรูปภาพข้อความ ยกเว้นกรณีจำเป็น (โลโก้) หรือผู้ใช้ปรับแต่งได้",
    failCondition: "พบรูปภาพที่เป็นข้อความโดยไม่จำเป็นและไม่สามารถแทนที่ด้วยข้อความจริงได้",
    disabilityTypes: ["low_vision"],
    assistiveTech: ["magnifier"],
    applicableWhen: "หน้ามีรูปภาพที่มีข้อความอยู่ในภาพ",
    isActive: true,
  },
  {
    libId: "LIB-017",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.10",
    wcagTitle: "Reflow",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบการจัดเรียงเนื้อหาใหม่ (Reflow) ที่ 320px",
    description: "ตรวจสอบว่าเนื้อหาจัดเรียงใหม่ในแนวตั้งเดียวได้เมื่อขยาย/ย่อจอเทียบเท่าความกว้าง 320px โดยไม่ต้องเลื่อนสองทิศทาง",
    steps: ["ปรับขนาดหน้าจอ/ซูมจนเทียบเท่า 320px width (400% zoom)", "ตรวจสอบว่าเนื้อหาจัดเรียงใหม่ (reflow) โดยไม่ต้องเลื่อนแนวนอน"],
    expectedResult: "เนื้อหาแสดงผลได้ครบถ้วนในแนวตั้งเดียว ไม่ต้องเลื่อนสองทิศทาง",
    failCondition: "ต้องเลื่อนแนวนอนเพื่ออ่านเนื้อหาปกติ (ยกเว้นตาราง/แผนที่ที่จำเป็น)",
    disabilityTypes: ["low_vision"],
    assistiveTech: ["magnifier"],
    applicableWhen: "ทุกหน้า โดยเฉพาะที่ใช้งานบนมือถือ/จอเล็ก",
    isActive: true,
  },
  {
    libId: "LIB-018",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.11",
    wcagTitle: "Non-text Contrast",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ Contrast ของ UI Component และไอคอน",
    description: "ตรวจสอบว่า UI component (ปุ่ม, ช่อง input, checkbox) และ graphical object ที่จำเป็นมี contrast เพียงพอต่อพื้นหลังโดยรอบ",
    steps: ["ตรวจสอบ contrast ของขอบ/พื้นหลัง UI component (ปุ่ม, checkbox, input border) เทียบพื้นหลังโดยรอบ", "ตรวจสอบ icon ที่สื่อสถานะ"],
    expectedResult: "UI component และ graphical object ที่จำเป็นต่อการใช้งานมี contrast อย่างน้อย 3:1",
    failCondition: "ขอบ/ไอคอน UI มองไม่เห็นชัดเจนเพราะ contrast ต่ำกว่า 3:1",
    disabilityTypes: ["low_vision"],
    assistiveTech: ["magnifier"],
    applicableWhen: "หน้ามี UI component เช่นปุ่ม, ช่อง input, ไอคอนสถานะ",
    isActive: true,
  },
  {
    libId: "LIB-019",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.12",
    wcagTitle: "Text Spacing",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบเนื้อหาเมื่อปรับ Text Spacing",
    description: "ตรวจสอบว่าเนื้อหายังแสดงผลได้ครบถ้วนเมื่อผู้ใช้ปรับ line-height, paragraph spacing, letter spacing, word spacing ตามค่าที่ WCAG กำหนด",
    steps: ["ใช้ bookmarklet/extension ปรับ text spacing ตามค่าที่ WCAG กำหนด (line-height 1.5x, paragraph spacing 2x, letter spacing 0.12x, word spacing 0.16x)", "ตรวจสอบว่าเนื้อหาไม่ถูกตัด/ซ้อนทับ"],
    expectedResult: "เนื้อหาแสดงผลได้ครบถ้วนแม้ปรับ spacing ตามค่าที่กำหนด",
    failCondition: "ข้อความถูกตัด ซ้อนทับ หรืออ่านไม่ได้เมื่อปรับ text spacing",
    disabilityTypes: ["low_vision", "cognitive"],
    assistiveTech: ["magnifier"],
    applicableWhen: "ทุกหน้าที่มีข้อความ",
    isActive: true,
  },
  {
    libId: "LIB-020",
    wcagVersion: "2.2",
    wcagCriterion: "1.4.13",
    wcagTitle: "Content on Hover or Focus",
    wcagLevel: "AA",
    wcagPrinciple: "Perceivable",
    title: "ตรวจสอบ Tooltip/Popup ที่แสดงเมื่อ Hover หรือ Focus",
    description: "ตรวจสอบว่าเนื้อหาเพิ่มเติมที่ปรากฏเมื่อ hover/focus (tooltip, popup) dismiss ได้, hoverable ได้ และไม่หายไปเอง",
    steps: ["hover/focus ที่ element ที่แสดงเนื้อหาเพิ่มเติม", "ตรวจสอบว่าสามารถเลื่อนเมาส์ไปยังเนื้อหาที่ปรากฏได้โดยไม่หายไป, ปิดได้ด้วย Esc, และไม่หายไปเองจนกว่าจะ hover ออก"],
    expectedResult: "เนื้อหาที่ปรากฏสามารถ dismiss ได้, hoverable ได้, และคงอยู่จนกว่าผู้ใช้จะ dismiss/ย้าย focus",
    failCondition: "เนื้อหาหายไปเองก่อนอ่านจบ, dismiss ไม่ได้ด้วยคีย์บอร์ด, หรือ hover ไปที่เนื้อหาไม่ได้",
    disabilityTypes: ["low_vision", "motor"],
    assistiveTech: ["magnifier", "keyboard"],
    applicableWhen: "หน้ามี tooltip/popup ที่แสดงเมื่อ hover หรือ focus",
    isActive: true,
  },

  // ─── 2. Operable ──────────────────────────────────────────────────────
  {
    libId: "LIB-021",
    wcagVersion: "2.2",
    wcagCriterion: "2.1.1",
    wcagTitle: "Keyboard",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบการใช้งานทุกฟังก์ชันด้วยคีย์บอร์ด",
    description: "ตรวจสอบว่าทุกฟังก์ชันในหน้าสามารถใช้งานได้ครบถ้วนด้วยคีย์บอร์ดเพียงอย่างเดียว โดยไม่ต้องพึ่งเมาส์",
    steps: ["ถอดเมาส์ออกหรืองดใช้", "ใช้ Tab/Shift+Tab/Enter/Space/Arrow keys ไล่ใช้งานฟังก์ชันทั้งหมดในหน้า"],
    expectedResult: "ทุกฟังก์ชันสามารถใช้งานได้ครบถ้วนด้วยคีย์บอร์ดเพียงอย่างเดียว",
    failCondition: "มีฟังก์ชันที่ใช้งานได้เฉพาะเมาส์เท่านั้น",
    disabilityTypes: ["motor", "blind"],
    assistiveTech: ["keyboard", "switch_access"],
    applicableWhen: "ทุก interactive element ในหน้า",
    isActive: true,
  },
  {
    libId: "LIB-022",
    wcagVersion: "2.2",
    wcagCriterion: "2.1.2",
    wcagTitle: "No Keyboard Trap",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบว่าไม่มี Keyboard Trap",
    description: "ตรวจสอบว่าโฟกัสของคีย์บอร์ดสามารถเข้าและออกจาก component ทุกตัวได้ ไม่ติดค้างอยู่ภายใน",
    steps: ["ใช้ Tab ไล่เข้าไปใน modal/widget ทุกจุด", "ตรวจสอบว่าสามารถ Tab ออกจาก component นั้นได้"],
    expectedResult: "โฟกัสสามารถเข้าและออกจากทุก component ได้ด้วยคีย์บอร์ดปกติ",
    failCondition: "โฟกัสติดอยู่ใน component และออกไม่ได้ด้วยคีย์บอร์ดมาตรฐาน",
    disabilityTypes: ["motor"],
    assistiveTech: ["keyboard"],
    applicableWhen: "หน้ามี modal, widget, หรือ embedded content",
    isActive: true,
  },
  {
    libId: "LIB-023",
    wcagVersion: "2.2",
    wcagCriterion: "2.1.4",
    wcagTitle: "Character Key Shortcuts",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบ Keyboard Shortcut แบบตัวอักษรเดี่ยว",
    description: "ตรวจสอบว่า shortcut ที่ใช้ตัวอักษรเดี่ยวสามารถปิด/ปรับ remap ได้ หรือทำงานเฉพาะตอน component มี focus",
    steps: ["ทดสอบกดตัวอักษรเดี่ยวที่เป็น shortcut ขณะ focus อยู่ในหน้า (ไม่ใช่ในช่อง input)", "ตรวจสอบว่ามีวิธีปิด/remap/จำกัด shortcut เฉพาะตอน focus component นั้น"],
    expectedResult: "shortcut ตัวอักษรเดี่ยวสามารถปิดได้ ปรับ remap ได้ หรือทำงานเฉพาะตอน component มี focus",
    failCondition: "shortcut ทำงานทันทีโดยไม่มีทางปิด/ปรับ ทำให้ผู้ใช้ speech input พิมพ์ผิดพลาดโดยไม่ตั้งใจ",
    disabilityTypes: ["motor", "cognitive"],
    assistiveTech: ["keyboard"],
    applicableWhen: "หน้ามี keyboard shortcut ที่เป็นตัวอักษรเดี่ยว (เช่น กด 's' เพื่อ save)",
    isActive: true,
  },
  {
    libId: "LIB-024",
    wcagVersion: "2.2",
    wcagCriterion: "2.2.1",
    wcagTitle: "Timing Adjustable",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบการปรับ/ขยายเวลาที่จำกัด",
    description: "ตรวจสอบว่าข้อจำกัดด้านเวลา (session timeout ฯลฯ) สามารถปิด ปรับ หรือขยายได้ก่อนหมดเวลา",
    steps: ["ตรวจสอบว่ามี time limit ในหน้า (เช่น session timeout)", "ตรวจสอบว่าสามารถปิด, ปรับ, หรือขยายเวลาได้ก่อนหมดเวลา"],
    expectedResult: "ผู้ใช้สามารถปิด ปรับ หรือขยายเวลาที่จำกัดได้ (อย่างน้อย 10 เท่าของค่าเริ่มต้น)",
    failCondition: "ระบบ timeout โดยไม่มีทางเลือกให้ขยาย/ปิดเวลา",
    disabilityTypes: ["cognitive", "motor", "blind"],
    assistiveTech: ["screen_reader", "keyboard"],
    applicableWhen: "หน้ามี session timeout หรือเวลาจำกัดในการทำรายการ",
    isActive: true,
  },
  {
    libId: "LIB-025",
    wcagVersion: "2.2",
    wcagCriterion: "2.2.2",
    wcagTitle: "Pause, Stop, Hide",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบการหยุด/ซ่อนเนื้อหาเคลื่อนไหวอัตโนมัติ",
    description: "ตรวจสอบว่าเนื้อหาที่เคลื่อนไหว/เลื่อน/อัปเดตอัตโนมัตินานกว่า 5 วินาทีมีปุ่ม pause/stop/hide",
    steps: ["สังเกตเนื้อหาที่เคลื่อนไหว/เลื่อน/อัปเดตอัตโนมัตินานกว่า 5 วินาที", "ตรวจสอบว่ามีปุ่ม pause/stop/hide ที่เข้าถึงได้"],
    expectedResult: "ผู้ใช้สามารถ pause, stop หรือ hide เนื้อหาที่เคลื่อนไหวอัตโนมัติได้",
    failCondition: "เนื้อหาเคลื่อนไหวต่อเนื่องโดยไม่มีทาง pause/stop/hide",
    disabilityTypes: ["cognitive", "low_vision"],
    assistiveTech: ["keyboard"],
    applicableWhen: "หน้ามีเนื้อหาเคลื่อนไหว/เลื่อนอัตโนมัติ (carousel, marquee, auto-update)",
    isActive: true,
  },
  {
    libId: "LIB-026",
    wcagVersion: "2.2",
    wcagCriterion: "2.3.1",
    wcagTitle: "Three Flashes or Below Threshold",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบเนื้อหากระพริบ/แฟลช",
    description: "ตรวจสอบว่าไม่มีเนื้อหาที่กระพริบเกิน 3 ครั้งต่อวินาทีในพื้นที่ที่มีขนาดเสี่ยงต่อการชักจากแสง",
    steps: ["สังเกตเนื้อหาที่กระพริบ", "นับความถี่การกระพริบต่อวินาที"],
    expectedResult: "ไม่มีเนื้อหาที่กระพริบเกิน 3 ครั้งต่อวินาที หรืออยู่ต่ำกว่าเกณฑ์ general/red flash threshold",
    failCondition: "พบเนื้อหากระพริบเกิน 3 ครั้ง/วินาทีในพื้นที่ที่มีขนาดเสี่ยง",
    disabilityTypes: ["cognitive"],
    assistiveTech: [],
    applicableWhen: "หน้ามีเนื้อหากระพริบ/แฟลช (แอนิเมชัน, โฆษณา, วิดีโอ)",
    isActive: true,
  },
  {
    libId: "LIB-027",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.1",
    wcagTitle: "Bypass Blocks",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบ Skip Link ข้ามเนื้อหาซ้ำ",
    description: "ตรวจสอบว่ามีกลไกให้ข้ามบล็อกเนื้อหาที่ซ้ำกันในหลายหน้า (เช่น เมนู, header) ก่อนถึงเนื้อหาหลัก",
    steps: ["โหลดหน้าใหม่แล้วกด Tab ครั้งแรก", "ตรวจสอบว่ามีลิงก์ 'ข้ามไปเนื้อหาหลัก' (skip link) หรือใช้ landmark/heading แบ่งกลุ่มเนื้อหาได้"],
    expectedResult: "มีกลไกให้ข้ามบล็อกเนื้อหาที่ซ้ำกัน (skip link หรือ landmark) ก่อนถึงเนื้อหาหลัก",
    failCondition: "ไม่มี skip link และไม่มี landmark ให้ข้ามเมนู/หัวเรื่องซ้ำ",
    disabilityTypes: ["blind", "motor"],
    assistiveTech: ["screen_reader", "keyboard"],
    applicableWhen: "ทุกหน้าที่มี navigation/header ซ้ำกันหลายหน้า",
    isActive: true,
  },
  {
    libId: "LIB-028",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.2",
    wcagTitle: "Page Titled",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบชื่อหน้า (Page Title)",
    description: "ตรวจสอบว่าแต่ละหน้ามี <title> ที่สื่อความหมายและบอกหัวข้อ/วัตถุประสงค์ของหน้าได้ชัดเจน",
    steps: ["ตรวจสอบ <title> ของหน้าในแท็บ browser หรือที่ Screen Reader อ่านตอนโหลดหน้า"],
    expectedResult: "ชื่อหน้าสื่อความหมายและบอกหัวข้อ/วัตถุประสงค์ของหน้าได้ชัดเจน",
    failCondition: "ไม่มี title, title ซ้ำกันทุกหน้า หรือ title ไม่สื่อความหมาย",
    disabilityTypes: ["blind", "cognitive"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ทุกหน้า",
    isActive: true,
  },
  {
    libId: "LIB-029",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.3",
    wcagTitle: "Focus Order",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบลำดับการรับโฟกัส (Focus Order)",
    description: "ตรวจสอบว่าลำดับโฟกัสของคีย์บอร์ดเป็นไปตามลำดับตรรกะของเนื้อหาที่แสดงผล",
    steps: ["กด Tab ไล่ทั้งหน้า", "ตรวจสอบว่าลำดับโฟกัสตรงกับลำดับที่แสดงผลและเนื้อหาที่มีความหมาย"],
    expectedResult: "ลำดับโฟกัสเป็นไปตามลำดับตรรกะของเนื้อหา ไม่กระโดดข้ามแบบสับสน",
    failCondition: "โฟกัสกระโดดข้ามไปมาไม่สัมพันธ์กับลำดับเนื้อหาที่แสดง",
    disabilityTypes: ["motor", "blind"],
    assistiveTech: ["keyboard", "screen_reader"],
    applicableWhen: "ทุกหน้าที่มี interactive element",
    isActive: true,
  },
  {
    libId: "LIB-030",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.4",
    wcagTitle: "Link Purpose (In Context)",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบข้อความลิงก์สื่อความหมาย",
    description: "ตรวจสอบว่าข้อความลิงก์ (หรือร่วมกับ context) สื่อจุดหมายปลายทางของลิงก์ได้ชัดเจน",
    steps: ["ใช้ Screen Reader เปิด list ของลิงก์ทั้งหมดในหน้า (เช่น NVDA Insert+F7)", "ตรวจสอบว่าแต่ละลิงก์สื่อจุดหมายปลายทางได้โดยไม่ต้องอ่าน context รอบข้าง"],
    expectedResult: "ข้อความลิงก์ (หรือ aria-label) สื่อความหมายจุดหมายปลายทางได้ชัดเจน",
    failCondition: "พบลิงก์ข้อความกำกวมเช่น 'คลิกที่นี่', 'อ่านต่อ' โดยไม่มี context หรือ aria-label เสริม",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีลิงก์",
    isActive: true,
  },
  {
    libId: "LIB-031",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.5",
    wcagTitle: "Multiple Ways",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบว่ามีหลายวิธีเข้าถึงหน้า",
    description: "ตรวจสอบว่าเว็บไซต์มีมากกว่า 1 วิธีในการค้นหา/เข้าถึงแต่ละหน้า เช่น เมนู, search, sitemap",
    steps: ["ตรวจสอบว่ามีมากกว่า 1 วิธีในการค้นหาหน้า เช่น เมนู, search, sitemap, breadcrumb"],
    expectedResult: "มีอย่างน้อย 2 วิธีที่แตกต่างกันในการเข้าถึงหน้าแต่ละหน้า",
    failCondition: "มีเพียงวิธีเดียวในการเข้าถึงหน้า (เช่น ต้องเดิน flow เดียวเท่านั้น)",
    disabilityTypes: ["cognitive", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "เว็บไซต์ที่มีมากกว่า 1 หน้า (ไม่ใช่ single-step process)",
    isActive: true,
  },
  {
    libId: "LIB-032",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.6",
    wcagTitle: "Headings and Labels",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบ Heading และ Label สื่อความหมาย",
    description: "ตรวจสอบว่า heading และ form label อธิบายเนื้อหา/จุดประสงค์ที่ตามมาได้อย่างชัดเจนและถูกต้อง",
    steps: ["ตรวจสอบ heading และ label ของฟอร์มทุกจุด", "ประเมินว่าสื่อความหมาย/หัวข้อของเนื้อหาที่ตามมาได้ชัดเจน"],
    expectedResult: "Heading และ label อธิบายเนื้อหา/จุดประสงค์ได้อย่างชัดเจนและถูกต้อง",
    failCondition: "heading/label ทั่วไปเกินไป (เช่น 'หัวข้อ1') หรือไม่ตรงกับเนื้อหาจริง",
    disabilityTypes: ["blind", "cognitive"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ทุกหน้าที่มี heading หรือ form label",
    isActive: true,
  },
  {
    libId: "LIB-033",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.7",
    wcagTitle: "Focus Visible",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบตัวบ่งชี้โฟกัสที่มองเห็นได้",
    description: "ตรวจสอบว่าทุก element ที่ได้รับโฟกัสจากคีย์บอร์ดแสดง visual indicator ที่มองเห็นได้ชัดเจน",
    steps: ["กด Tab ไล่ทุก element ที่รับโฟกัสได้", "สังเกตว่ามี visual indicator (outline/highlight) ชัดเจนว่า element ใดกำลังมีโฟกัส"],
    expectedResult: "ทุก element ที่ได้รับโฟกัสแสดง indicator ที่มองเห็นได้ชัดเจน",
    failCondition: "element ที่ได้โฟกัสไม่มี visual indicator หรือถูกซ่อนด้วย CSS (outline: none) โดยไม่มีทางเลือกอื่นแทน",
    disabilityTypes: ["motor", "low_vision"],
    assistiveTech: ["keyboard"],
    applicableWhen: "ทุก interactive element",
    isActive: true,
  },
  {
    libId: "LIB-034",
    wcagVersion: "2.2",
    wcagCriterion: "2.4.11",
    wcagTitle: "Focus Not Obscured (Minimum)",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบว่า Element ที่มีโฟกัสไม่ถูกบัง",
    description: "ตรวจสอบว่า element ที่ได้รับโฟกัสไม่ถูกบังทั้งหมดโดย sticky header/footer หรือ overlay อื่น",
    steps: ["กด Tab ไล่ element ที่อยู่ใกล้ sticky header/footer หรือใต้ overlay", "ตรวจสอบว่า element ที่ได้โฟกัสไม่ถูกบังทั้งหมดโดย component อื่น"],
    expectedResult: "element ที่มีโฟกัสไม่ถูกบังทั้งหมดโดย sticky content หรือ overlay อื่น",
    failCondition: "element ที่ได้โฟกัสถูกซ่อนทั้งหมดอยู่หลัง sticky header/footer หรือ overlay",
    disabilityTypes: ["motor", "low_vision"],
    assistiveTech: ["keyboard"],
    applicableWhen: "หน้ามี sticky header/footer หรือ overlay ที่อาจบัง element ที่ focus",
    isActive: true,
  },
  {
    libId: "LIB-035",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.1",
    wcagTitle: "Pointer Gestures",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบทางเลือกสำหรับ Gesture ซับซ้อน",
    description: "ตรวจสอบว่าฟังก์ชันที่ใช้ gesture ซับซ้อน (multipoint/path-based เช่น swipe, pinch) มีทางเลือกใช้ single-pointer แบบง่ายแทน",
    steps: ["ทดสอบฟังก์ชันที่ใช้ gesture ซับซ้อน (multipoint/path-based)", "ตรวจสอบว่ามีทางเลือกใช้ single-pointer แบบง่าย (เช่น ปุ่ม) แทน"],
    expectedResult: "ทุกฟังก์ชันที่ใช้ gesture ซับซ้อนมีทางเลือก single-pointer ที่ไม่ต้องใช้ multi-touch/path",
    failCondition: "ฟังก์ชันใช้งานได้เฉพาะผ่าน gesture ซับซ้อนเท่านั้น",
    disabilityTypes: ["motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "หน้ามี gesture ซับซ้อน เช่น swipe, pinch, multi-touch",
    isActive: true,
  },
  {
    libId: "LIB-036",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.2",
    wcagTitle: "Pointer Cancellation",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบการยกเลิก Action ก่อนปล่อยเมาส์/นิ้ว",
    description: "ตรวจสอบว่า action ที่ trigger ด้วย pointer ทำงานที่ event 'ปล่อย' ไม่ใช่ 'กดลง' และสามารถยกเลิกได้",
    steps: ["กด mouse/touch ลงบนปุ่มแล้วลากออกก่อนปล่อย (down-then-drag-away)", "ตรวจสอบว่า action ไม่ทำงานจนกว่าจะปล่อยขณะยังอยู่บน element (up event)"],
    expectedResult: "Action ทำงานที่ event 'ปล่อย' (up) ไม่ใช่ 'กดลง' (down) และสามารถยกเลิกได้โดยลากออกก่อนปล่อย",
    failCondition: "Action ทำงานทันทีที่กดลง (down event) ทำให้ผู้ใช้ที่มือสั่นกดผิดพลาดโดยไม่สามารถยกเลิกได้",
    disabilityTypes: ["motor"],
    assistiveTech: [],
    applicableWhen: "หน้ามีปุ่ม/ลิงก์ที่ trigger action ด้วย pointer",
    isActive: true,
  },
  {
    libId: "LIB-037",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.3",
    wcagTitle: "Label in Name",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบว่า Accessible Name มี Visible Label อยู่ด้วย",
    description: "ตรวจสอบว่า accessible name (เช่น aria-label) มีข้อความ visible label ปรากฏอยู่ เพื่อให้ผู้ใช้ voice control สั่งงานได้",
    steps: ["ตรวจสอบ visible label ของปุ่ม/ลิงก์", "เปรียบเทียบกับ accessible name (aria-label) ที่ Screen Reader อ่าน"],
    expectedResult: "accessible name มีข้อความ visible label ปรากฏอยู่ (ตรงกันหรือเป็นส่วนหนึ่ง)",
    failCondition: "accessible name ไม่ตรงหรือไม่มี visible label อยู่ในนั้น ทำให้ผู้ใช้ voice control สั่งงานไม่ได้",
    disabilityTypes: ["motor", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามี element ที่มีทั้ง visible label และ accessible name (เช่นปุ่มที่ใช้ voice control)",
    isActive: true,
  },
  {
    libId: "LIB-038",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.4",
    wcagTitle: "Motion Actuation",
    wcagLevel: "A",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบทางเลือกสำหรับฟังก์ชันที่ใช้ Motion",
    description: "ตรวจสอบว่าฟังก์ชันที่ทำงานด้วยการเขย่า/เอียงอุปกรณ์มีทางเลือกใช้ UI control แทน และปิด motion trigger ได้",
    steps: ["ทดสอบฟังก์ชันที่ trigger ด้วย motion (shake, tilt)", "ตรวจสอบว่ามีปุ่ม UI ทางเลือกให้ทำ action เดียวกัน และสามารถปิด motion trigger ได้"],
    expectedResult: "มีทางเลือกใช้ UI control แทน motion และสามารถปิดการตอบสนองต่อ motion ได้",
    failCondition: "ฟังก์ชันทำงานได้เฉพาะผ่านการเขย่า/เอียงอุปกรณ์เท่านั้น",
    disabilityTypes: ["motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "หน้า/แอปมีฟังก์ชันที่ทำงานด้วยการเขย่า/เอียงอุปกรณ์",
    isActive: true,
  },
  {
    libId: "LIB-039",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.7",
    wcagTitle: "Dragging Movements",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบทางเลือกสำหรับฟังก์ชัน Drag-and-Drop",
    description: "ตรวจสอบว่าฟังก์ชัน drag-and-drop มีทางเลือกทำ action เดียวกันด้วย single-pointer แบบไม่ต้องลาก",
    steps: ["ทดสอบฟังก์ชัน drag-and-drop", "ตรวจสอบว่ามีทางเลือกทำ action เดียวกันด้วย single-pointer แบบไม่ต้องลาก (เช่น ปุ่มลูกศร, click-to-select)"],
    expectedResult: "มีทางเลือกที่ไม่ต้องใช้ dragging เพื่อให้ผลลัพธ์เดียวกัน",
    failCondition: "ฟังก์ชันใช้งานได้เฉพาะการลาก (drag) เท่านั้น ไม่มีทางเลือกอื่น",
    disabilityTypes: ["motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "หน้ามีฟังก์ชัน drag-and-drop (เช่น slider, reorder list, drag to upload)",
    isActive: true,
  },
  {
    libId: "LIB-040",
    wcagVersion: "2.2",
    wcagCriterion: "2.5.8",
    wcagTitle: "Target Size (Minimum)",
    wcagLevel: "AA",
    wcagPrinciple: "Operable",
    title: "ตรวจสอบขนาดพื้นที่กดขั้นต่ำ (Target Size)",
    description: "ตรวจสอบว่า target ที่ต้องกด (ปุ่ม, ลิงก์, ไอคอน) มีขนาดอย่างน้อย 24x24 CSS pixel หรือเข้าเงื่อนไขข้อยกเว้น",
    steps: ["วัดขนาด clickable target ของปุ่ม/ไอคอนที่มีระยะห่างจาก target อื่นน้อย", "ตรวจสอบขนาดอย่างน้อย 24x24 CSS pixel หรือมีระยะห่างเพียงพอ/มีข้อยกเว้นที่เข้าเงื่อนไข"],
    expectedResult: "target มีขนาดอย่างน้อย 24x24px หรือเข้าเงื่อนไขข้อยกเว้น (inline, equivalent, essential)",
    failCondition: "target เล็กกว่า 24x24px และอยู่ชิดกับ target อื่นจนกดพลาดง่าย",
    disabilityTypes: ["motor"],
    assistiveTech: ["switch_access"],
    applicableWhen: "หน้ามีปุ่ม/ลิงก์/target ที่ต้องกด",
    isActive: true,
  },

  // ─── 3. Understandable ────────────────────────────────────────────────
  {
    libId: "LIB-041",
    wcagVersion: "2.2",
    wcagCriterion: "3.1.1",
    wcagTitle: "Language of Page",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบ Language Attribute ของหน้า",
    description: "ตรวจสอบว่า <html lang=\"...\"> ระบุภาษาหลักของหน้าถูกต้อง เพื่อให้ Screen Reader ออกเสียงถูกสำเนียง",
    steps: ["ตรวจสอบ attribute lang ของ <html>", "ทดสอบให้ Screen Reader อ่านหน้าและฟังว่าออกเสียงถูกต้องตามภาษา"],
    expectedResult: "<html lang=\"...\"> ระบุภาษาหลักของหน้าถูกต้อง",
    failCondition: "ไม่มี lang attribute หรือระบุภาษาผิด ทำให้ Screen Reader ออกเสียงผิดสำเนียง",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ทุกหน้า",
    isActive: true,
  },
  {
    libId: "LIB-042",
    wcagVersion: "2.2",
    wcagCriterion: "3.1.2",
    wcagTitle: "Language of Parts",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบ Language Attribute ของข้อความภาษาอื่นในหน้า",
    description: "ตรวจสอบว่าข้อความส่วนที่เป็นภาษาอื่นจากภาษาหลักของหน้า (เช่น คำศัพท์อังกฤษในหน้าไทย) มี lang attribute กำกับ",
    steps: ["ตรวจสอบ segment ข้อความที่เป็นภาษาอื่นจากภาษาหลักของหน้า", "ตรวจสอบว่ามี lang attribute กำกับ segment นั้น"],
    expectedResult: "ข้อความส่วนที่เป็นภาษาอื่นมี lang attribute กำกับให้ Screen Reader ออกเสียงถูกต้อง",
    failCondition: "ข้อความภาษาอื่นไม่มี lang attribute กำกับ ทำให้ออกเสียงผิด",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามีข้อความที่เป็นภาษาอื่นแทรกอยู่ (เช่น คำศัพท์อังกฤษในหน้าไทย)",
    isActive: true,
  },
  {
    libId: "LIB-043",
    wcagVersion: "2.2",
    wcagCriterion: "3.2.1",
    wcagTitle: "On Focus",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบว่าการรับโฟกัสไม่เปลี่ยนแปลง Context โดยไม่คาดคิด",
    description: "ตรวจสอบว่าการที่ element ได้รับโฟกัสไม่ทำให้เกิดการเปลี่ยนแปลง context (เปิดหน้าใหม่, submit form) โดยผู้ใช้ไม่ได้กระทำเพิ่ม",
    steps: ["Tab ไปที่แต่ละ element ทีละตัว", "สังเกตว่าเกิดการเปลี่ยนแปลง context ทันที (เปิดหน้าใหม่, submit form, เปลี่ยน focus โดยไม่คาดคิด) หรือไม่"],
    expectedResult: "การได้รับโฟกัสไม่ทำให้เกิดการเปลี่ยนแปลง context โดยไม่คาดคิด",
    failCondition: "แค่ Tab เข้าไปที่ element ก็ทำให้หน้าเปลี่ยน/popup เปิดโดยผู้ใช้ไม่ได้กระทำเพิ่ม",
    disabilityTypes: ["cognitive", "motor"],
    assistiveTech: ["keyboard"],
    applicableWhen: "ทุก interactive element",
    isActive: true,
  },
  {
    libId: "LIB-044",
    wcagVersion: "2.2",
    wcagCriterion: "3.2.2",
    wcagTitle: "On Input",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบว่าการกรอก/เลือกค่าไม่เปลี่ยนแปลง Context โดยไม่แจ้งเตือน",
    description: "ตรวจสอบว่าการเปลี่ยนค่าใน input/select ไม่ทำให้เกิดการเปลี่ยนแปลง context ทันทีโดยไม่แจ้งเตือนล่วงหน้า",
    steps: ["กรอกข้อมูล/เลือกค่าใน field ต่างๆ โดยไม่กด submit", "สังเกตว่าเกิดการเปลี่ยนแปลง context ทันที (submit form, เปลี่ยนหน้า) หรือไม่"],
    expectedResult: "การเปลี่ยนค่าใน input ไม่ทำให้เกิดการเปลี่ยนแปลง context โดยไม่แจ้งเตือนล่วงหน้า",
    failCondition: "เลือกค่าใน dropdown แล้วระบบ submit/เปลี่ยนหน้าทันทีโดยไม่มีการแจ้งเตือน",
    disabilityTypes: ["cognitive", "motor"],
    assistiveTech: [],
    applicableWhen: "หน้ามี form input/select",
    isActive: true,
  },
  {
    libId: "LIB-045",
    wcagVersion: "2.2",
    wcagCriterion: "3.2.3",
    wcagTitle: "Consistent Navigation",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบความสม่ำเสมอของเมนู Navigation",
    description: "ตรวจสอบว่าเมนู navigation ที่ปรากฏซ้ำในหลายหน้าเรียงลำดับเหมือนกันทุกหน้า",
    steps: ["เปรียบเทียบตำแหน่งและลำดับของเมนู navigation ในหลายหน้า"],
    expectedResult: "เมนู navigation ที่ซ้ำกันเรียงลำดับเหมือนกันทุกหน้า",
    failCondition: "ลำดับ/ตำแหน่งเมนูเปลี่ยนไปในแต่ละหน้าโดยไม่มีเหตุผล",
    disabilityTypes: ["cognitive", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "เว็บไซต์ที่มีหลายหน้าและมีเมนู/navigation ซ้ำกัน",
    isActive: true,
  },
  {
    libId: "LIB-046",
    wcagVersion: "2.2",
    wcagCriterion: "3.2.4",
    wcagTitle: "Consistent Identification",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบความสม่ำเสมอของชื่อ/ไอคอน Component",
    description: "ตรวจสอบว่า component ที่ทำหน้าที่เดียวกันในหลายหน้ามีชื่อ/ไอคอน/label เหมือนกันตลอดทั้งเว็บไซต์",
    steps: ["เปรียบเทียบไอคอน/label ของ component ที่ทำหน้าที่เดียวกันในหลายหน้า (เช่นปุ่มค้นหา)"],
    expectedResult: "Component ที่ทำหน้าที่เดียวกันมีชื่อ/ไอคอน/label เหมือนกันตลอดทั้งเว็บไซต์",
    failCondition: "component หน้าที่เดียวกันถูกเรียกชื่อหรือใช้ไอคอนต่างกันในแต่ละหน้า",
    disabilityTypes: ["cognitive", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "เว็บไซต์ที่มี component/ไอคอนที่ทำหน้าที่เดียวกันซ้ำในหลายหน้า",
    isActive: true,
  },
  {
    libId: "LIB-047",
    wcagVersion: "2.2",
    wcagCriterion: "3.2.6",
    wcagTitle: "Consistent Help",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบความสม่ำเสมอของตำแหน่งกลไกช่วยเหลือ",
    description: "ตรวจสอบว่ากลไกช่วยเหลือ (help, contact, chat) ที่ปรากฏในหลายหน้าอยู่ในตำแหน่งสัมพัทธ์เดียวกันตลอด",
    steps: ["เปรียบเทียบตำแหน่งของกลไกช่วยเหลือ (เช่น ปุ่ม chat, ลิงก์ติดต่อ) ในลำดับหน้าต่างๆ ของกระบวนการเดียวกัน"],
    expectedResult: "กลไกช่วยเหลืออยู่ในตำแหน่งเดียวกัน (ลำดับสัมพัทธ์เดียวกัน) ทุกหน้าที่ปรากฏ",
    failCondition: "ตำแหน่งกลไกช่วยเหลือเปลี่ยนไปมาในแต่ละหน้าโดยไม่มีเหตุผล",
    disabilityTypes: ["cognitive"],
    assistiveTech: [],
    applicableWhen: "เว็บไซต์ที่มีกลไกช่วยเหลือ (help, contact, chat) ปรากฏในหลายหน้า",
    isActive: true,
  },
  {
    libId: "LIB-048",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.1",
    wcagTitle: "Error Identification",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบการแจ้งข้อผิดพลาดของฟอร์ม",
    description: "ตรวจสอบว่าเมื่อกรอกฟอร์มผิดพลาด ระบบแจ้ง error เป็นข้อความที่ระบุ field ที่ผิดชัดเจน ไม่ใช่แค่สี",
    steps: ["กรอกข้อมูลผิดรูปแบบ/เว้นว่างช่องจำเป็น แล้ว submit", "ตรวจสอบว่ามีข้อความแจ้ง error ที่ระบุ field ที่ผิดชัดเจน และ Screen Reader ประกาศ error นั้น"],
    expectedResult: "มีข้อความ error ที่ระบุ field ที่ผิดพลาดเป็นข้อความ (ไม่ใช่แค่สี) และ Screen Reader ประกาศได้",
    failCondition: "ไม่มีข้อความ error หรือแจ้งด้วยสีอย่างเดียวโดยไม่มีข้อความ/Screen Reader ไม่ประกาศ",
    disabilityTypes: ["blind", "cognitive"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ฟอร์มที่มีการ validate ข้อมูล",
    isActive: true,
  },
  {
    libId: "LIB-049",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.2",
    wcagTitle: "Labels or Instructions",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบ Label/Instruction ของฟอร์ม",
    description: "ตรวจสอบว่าทุก field ในฟอร์มมี label หรือ instruction ที่ผูกกับ field นั้นแบบ programmatic (ไม่ใช่แค่ placeholder)",
    steps: ["ตรวจสอบว่าทุก input field มี label หรือ instruction ที่ผูกกับ field นั้น (programmatically associated)"],
    expectedResult: "ทุก field ที่ต้องกรอกมี label/instruction ที่ Screen Reader อ่านได้เมื่อ focus",
    failCondition: "field ไม่มี label หรือใช้ placeholder แทน label ทำให้หายไปเมื่อพิมพ์",
    disabilityTypes: ["blind", "cognitive"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ฟอร์มทุกช่อง",
    isActive: true,
  },
  {
    libId: "LIB-050",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.3",
    wcagTitle: "Error Suggestion",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบคำแนะนำแก้ไขข้อผิดพลาด",
    description: "ตรวจสอบว่าข้อความ error ให้คำแนะนำวิธีแก้ไขที่เจาะจง ไม่ใช่แค่บอกว่าผิด",
    steps: ["กรอกข้อมูลผิดรูปแบบแล้ว submit", "ตรวจสอบว่าข้อความ error แนะนำวิธีแก้ไข ไม่ใช่แค่บอกว่าผิด"],
    expectedResult: "ข้อความ error ให้คำแนะนำวิธีแก้ไขที่เจาะจง (เช่น รูปแบบที่ถูกต้องควรเป็นอย่างไร)",
    failCondition: "ข้อความ error บอกแค่ 'ข้อมูลไม่ถูกต้อง' โดยไม่มีคำแนะนำ",
    disabilityTypes: ["cognitive", "blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ฟอร์มที่มีการ validate ข้อมูลรูปแบบเฉพาะ (เช่น email, เบอร์โทร)",
    isActive: true,
  },
  {
    libId: "LIB-051",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.4",
    wcagTitle: "Error Prevention (Legal, Financial, Data)",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบขั้นตอนป้องกันข้อผิดพลาดในธุรกรรมสำคัญ",
    description: "ตรวจสอบว่ารายการที่มีผลผูกพันทางกฎหมาย/การเงิน/ข้อมูลสำคัญ มีขั้นตอนยืนยัน/ตรวจทาน/ย้อนกลับก่อน commit จริง",
    steps: ["ทำรายการที่มีผลผูกพัน (submit คำสั่งซื้อ, ลบข้อมูล)", "ตรวจสอบว่ามีขั้นตอนยืนยัน/ตรวจทาน/ยกเลิกก่อน commit จริง"],
    expectedResult: "มีกลไก reversible, ตรวจสอบข้อมูล, หรือยืนยันก่อนดำเนินการที่มีผลผูกพัน",
    failCondition: "ระบบ submit/ลบข้อมูลทันทีโดยไม่มีขั้นตอนยืนยันหรือย้อนกลับ",
    disabilityTypes: ["cognitive"],
    assistiveTech: [],
    applicableWhen: "ฟอร์มที่เกี่ยวข้องกับธุรกรรมทางกฎหมาย การเงิน หรือข้อมูลสำคัญที่ลบไม่ได้",
    isActive: true,
  },
  {
    libId: "LIB-052",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.7",
    wcagTitle: "Redundant Entry",
    wcagLevel: "A",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบการไม่ต้องกรอกข้อมูลซ้ำในกระบวนการเดียวกัน",
    description: "ตรวจสอบว่าข้อมูลที่ผู้ใช้เคยกรอกไปแล้วในกระบวนการหลายขั้นตอนถูก auto-fill หรือให้เลือกใช้ซ้ำได้ ไม่ต้องพิมพ์ใหม่",
    steps: ["กรอกข้อมูลในขั้นตอนแรกแล้วไปขั้นตอนถัดไปที่ต้องใช้ข้อมูลเดียวกัน", "ตรวจสอบว่าระบบ auto-fill หรือให้เลือกใช้ข้อมูลเดิมแทนการพิมพ์ซ้ำ"],
    expectedResult: "ข้อมูลที่กรอกไปแล้วถูก auto-fill หรือมีตัวเลือกใช้ซ้ำ ไม่ต้องพิมพ์ใหม่",
    failCondition: "ผู้ใช้ต้องพิมพ์ข้อมูลเดิมซ้ำในขั้นตอนเดียวกันโดยไม่มีทาง auto-fill/เลือกใช้ซ้ำ",
    disabilityTypes: ["cognitive", "motor"],
    assistiveTech: [],
    applicableWhen: "ฟอร์มหลายขั้นตอน (multi-step) ที่ผู้ใช้เคยกรอกข้อมูลเดียวกันมาก่อนในกระบวนการเดียวกัน",
    isActive: true,
  },
  {
    libId: "LIB-053",
    wcagVersion: "2.2",
    wcagCriterion: "3.3.8",
    wcagTitle: "Accessible Authentication (Minimum)",
    wcagLevel: "AA",
    wcagPrinciple: "Understandable",
    title: "ตรวจสอบทางเลือกยืนยันตัวตนที่ไม่ต้องอาศัยความจำ/การคำนวณ",
    description: "ตรวจสอบว่าขั้นตอน login/ยืนยันตัวตนมีทางเลือกที่ไม่ต้องพึ่ง cognitive function test ล้วนๆ เช่น รองรับ password manager/paste/biometric",
    steps: ["ทดสอบขั้นตอน login", "ตรวจสอบว่ามีวิธีอื่นนอกจาก cognitive function test (เช่น จำรหัสผ่าน, แก้โจทย์คณิตศาสตร์) เช่น การใช้ password manager, copy-paste, biometric"],
    expectedResult: "มีทางเลือกยืนยันตัวตนที่ไม่ต้องอาศัยความจำ/การคำนวณล้วน เช่น รองรับ paste, password manager, หรือ biometric",
    failCondition: "บังคับให้จำ/คำนวณโดยไม่มีทางเลือกอื่น เช่น บล็อกการ paste รหัสผ่าน",
    disabilityTypes: ["cognitive"],
    assistiveTech: [],
    applicableWhen: "หน้า login/สมัครสมาชิกที่ต้องยืนยันตัวตน",
    isActive: true,
  },

  // ─── 4. Robust ────────────────────────────────────────────────────────
  {
    libId: "LIB-054",
    wcagVersion: "2.2",
    wcagCriterion: "4.1.1",
    wcagTitle: "Parsing",
    wcagLevel: "A",
    wcagPrinciple: "Robust",
    title: "ตรวจสอบความถูกต้องของ HTML Markup",
    description:
      "ตรวจสอบว่า HTML ไม่มี error ร้ายแรง (duplicate id, tag เปิดไม่ปิด, nesting ผิดโครงสร้าง) ที่กระทบการประมวลผลของ Assistive Technology. " +
      "หมายเหตุ: เกณฑ์นี้ถูกถอดออกอย่างเป็นทางการใน WCAG 2.2 (obsolete เพราะบราวเซอร์สมัยใหม่จัดการ parsing เอง) แต่ยังคงมีประโยชน์สำหรับการตรวจสอบเชิงป้องกัน — ปิดใช้งาน (isActive: false) ได้หากต้องการให้ตรงสเปค 2.2 อย่างเคร่งครัด",
    steps: ["ตรวจสอบ HTML ด้วย validator", "ตรวจหา duplicate ID, tag ที่เปิดไม่ปิด, nesting ผิดโครงสร้าง"],
    expectedResult: "HTML ไม่มี error ร้ายแรงที่กระทบการประมวลผลของ Assistive Technology (ไม่มี duplicate id, tag ปิดครบ)",
    failCondition: "พบ duplicate id หรือ markup ผิดโครงสร้างจนกระทบการอ่านของ Screen Reader",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "ทุกหน้า (ตรวจสอบ HTML markup)",
    isActive: true,
  },
  {
    libId: "LIB-055",
    wcagVersion: "2.2",
    wcagCriterion: "4.1.2",
    wcagTitle: "Name, Role, Value",
    wcagLevel: "A",
    wcagPrinciple: "Robust",
    title: "ตรวจสอบ Name, Role, Value ของ Custom Component",
    description: "ตรวจสอบว่า custom UI component (dropdown, tab, modal ที่ไม่ใช่ native HTML element) มี name, role, state ที่ถูกต้องและอัปเดตตามสถานะจริง",
    steps: ["ตรวจสอบ custom component ด้วย Screen Reader/accessibility inspector", "ตรวจสอบว่ามี role, name, state (expanded/checked/selected) ที่ถูกต้องและอัปเดตตามสถานะจริง"],
    expectedResult: "ทุก UI component มี name, role, value/state ที่ Assistive Technology อ่านและตรวจจับการเปลี่ยนแปลงได้ถูกต้อง",
    failCondition: "custom component ไม่มี role/name หรือ state ไม่อัปเดตเมื่อสถานะเปลี่ยน (เช่น aria-expanded ไม่เปลี่ยนตอนเปิดเมนู)",
    disabilityTypes: ["blind", "motor"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามี custom UI component (เช่น custom dropdown, tab, modal ที่ไม่ใช่ native HTML element)",
    isActive: true,
  },
  {
    libId: "LIB-056",
    wcagVersion: "2.2",
    wcagCriterion: "4.1.3",
    wcagTitle: "Status Messages",
    wcagLevel: "AA",
    wcagPrinciple: "Robust",
    title: "ตรวจสอบการประกาศ Status Message โดยไม่ต้องย้ายโฟกัส",
    description: "ตรวจสอบว่าข้อความสถานะ (เช่น 'บันทึกสำเร็จ', ผลการค้นหา) ถูกประกาศให้ Screen Reader ทราบโดยไม่ต้องย้ายโฟกัสไปหา",
    steps: ["ทำ action ที่ทำให้เกิด status message (เช่น submit form สำเร็จ, ค้นหาแล้วได้ผลลัพธ์)", "ฟังว่า Screen Reader ประกาศข้อความสถานะโดยอัตโนมัติหรือไม่ (ผ่าน aria-live/role=status)"],
    expectedResult: "Screen Reader ประกาศข้อความสถานะโดยอัตโนมัติผ่าน aria-live/role=status โดยไม่ต้องย้ายโฟกัส",
    failCondition: "ข้อความสถานะปรากฏบนหน้าจอแต่ Screen Reader ไม่ประกาศ (ไม่มี aria-live/role=status)",
    disabilityTypes: ["blind"],
    assistiveTech: ["screen_reader"],
    applicableWhen: "หน้ามี dynamic status message ที่ปรากฏโดยไม่โหลดหน้าใหม่",
    isActive: true,
  },
];

async function main() {
  await connectToDatabase();

  let created = 0;
  let updated = 0;

  for (const entry of LIBRARY_SEED) {
    const existing = await TestCaseLibrary.findOneAndUpdate(
      { libId: entry.libId },
      { $set: entry },
      { upsert: true, new: false, setDefaultsOnInsert: true }
    );
    if (existing) {
      updated++;
    } else {
      created++;
    }
  }

  console.log(
    `[seed-library] Done. Created: ${created}, Updated: ${updated}, Total in seed: ${LIBRARY_SEED.length}`
  );
}

main()
  .catch((err) => {
    console.error("[seed-library] Failed:", err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
